# 应用服务配置
server:
  port: 8080

spring:
  application:
    name: RentHouse
  #  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/house?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #  开发工具热启动配置
  devtools:
    livereload:
      enabled: true
  #  redis:
  #    host: 127.0.0.1
  #    port: 6379
  #    database: 0
  #    timeout: 10000
  #    password:
  #    jedis:
  #      pool:
  #        max-idle: 8
  #        max-active: 8
  #        min-idle: 0
  #  邮件配置
  #  邮箱授权码163邮箱为【邮箱+授权码】，126邮箱为【邮箱+密码】，qq邮箱为【邮箱+授权码】
  mail:
    host: smtp.qq.com
    username:
    password:

# 阿里云短信配置
# SMS控制台: https://dysms.console.aliyun.com
#aliyun:
#  sms:
#    sms-access-key-id: xxx
#    sms-access-key-secret: xxx
#    sms-endpoint: dysmsapi.aliyuncs.com
#    sms-template-code: SMS_154950909
#    sms-sign-name: 阿里云短信测试

# mybatis-plus开启日志
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 实体类的主键生成策略都是采用ASSIGN_ID(默认雪花算法id)
      id-type: assign_id
      logic-delete-value: 1 # 逻辑删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)


# log4j日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    # mybatis-plus日志, 只在debug模式下打印sql, 否则不打印(生产环境不打印)
    com.baomidou.mybatisplus: debug